export const UPDATE_POSTS = 'UPDATE_POSTS'
export const UPDATE_POST = 'UPDATE_POST'
export const ADD_POST = 'ADD_POST'
export const REMOVE_POST = 'REMOVE_POST'
export const ADD_POST_REPLIES = 'ADD_POST_REPLIES'